server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: digital-wallet-api
  profiles:
    active: ${APP_ENV:dev}
  threads:
    virtual:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration-seconds: 900
    refresh-token-expiration-seconds: 604800

