spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-falling-grass-b317h7w6-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_rD2Tnzxoft6J}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 15000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:live-yeti-319474.upstash.io}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:gQAAAAAABN_yAAIgcDE0MmU1MTExNTA5Yzk0MjExOWY3YWUxNTgyZjQ0YzUwYw}
      ssl:
        enabled: ${REDIS_SSL:true}
      timeout: 5000ms

logging:
  level:
    com.walletapp: DEBUG
    org.flywaydb: INFO
